default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_datetime:
  maquina_horario_agendado:
    name: "Horário Agendado"
    has_date: false
    has_time: true
  maquina_ultimo_acionamento:
    name: "Último Acionamento"
    has_date: true
    has_time: true

input_boolean:
  maquina_agendamento_ativo:
    name: "Agendamento Ativo"
    icon: mdi:washing-machine

mqtt:
  button:
    - name: "Acionar Máquina de Lavar"
      command_topic: "casa/maquinaLavar/activate"
      payload_press: "ON"
  binary_sensor:
    - name: "Máquina Feedback"
      state_topic: "casa/maquinaLavar/feedback"
      payload_on: "pressed"
      payload_off: "idle"
      off_delay: 5
    - name: "Máquina ESP Online"
      state_topic: "casa/maquinaLavar/heartbeat"
      payload_on: "alive"
      device_class: connectivity
      expire_after: 30
